### ISSUE TITLE
RgbaFloat Hex Conversion

### ISSUE THREAD

**Issue by rafaelvasco** [lithiumtoast/sokol-sharp#2]
(OSX Catalina 10.15.2)

Hey, found a bug in RgbaFloat implicit hex string conversion:

`uint.TryParse` as it is fails for some string hex codes. After doing some research the correct expression is: 

`uint.TryParse(hex.AsSpan(1), System.Globalization.NumberStyles.HexNumber, null, out var value);`

Did some quick testing with "#B0B0B0" which failed to parse before. After the fix it correctly parses and returns the correct value: 11579568.

Btw, Happy New Year !!

**Comment by lithiumtoast** [comment]
Yes, I have noticed that as well. I have that fix on my local branch. I'll push the changes now to `develop`.

**Comment by rafaelvasco** [comment]
Great. No problem :)
