### ISSUE TITLE
Sokol binaries

### ISSUE THREAD

**Issue by photex** [lithiumtoast/sokol-sharp#3]
Howdy! This is just a question while I'm on the road and can't check yet. I'm curious whether the sokol binaries are managed by this package or whether we'd have to provide them at runtime for the correct os and arch etc.

**Comment by photex** [comment]
Oh, just noticed the libs in the repo. Sorry for the spam!

**Comment by lithiumtoast** [comment]
Yup, I have the binaries for Sokol built manually and then committed to the repository. The Sokol binaries are then included as part of the NuGet package.
